# Generated by Django 4.2.7 on 2023-12-03 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Brand must be more than 3 char')])),
                ('color', models.TextField(max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='color must be more than 3 char'), django.core.validators.RegexValidator(message='Color accepts alphabets only', regex='^[a-zA-Z]+$')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='./static/image/uploaded_image')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
